### ISSUE TITLE
Typo or missing text in README.md

### ISSUE THREAD

**Issue by kimmalmo** [wimpysworld/obs-studio-portable#1]
On line 15, a sentence ends abruptly. I assume it should say something along the line of "executables, plugins and _**configurations**_.".

**Comment by troyBORG** [comment]
I noticed another error.
"You can copy the whole folder to a another computer and just use it."
shouldn't it be:
"You can copy the whole folder to another computer and just use it."

**Comment by kimmalmo** [comment]
@troyBORG Good catch! See #7
