### ISSUE TITLE
Not working on my PopOS Ubuntu 22.04

### ISSUE THREAD

**Issue by FilipStadler** [wimpysworld/obs-studio-portable#25]
It starts OBS but stops with following errors

warning: Failed to load 'da-DK' text for module: 'advanced-scene-switcher.so'
info: [adv-ss] version: 1.19.2
info: [adv-ss] version: 9bcced524bc456f3095b977f3af5966dfe14703e
info: [adv-ss] curl loaded successfully
info: [adv-ss] found curl library
info: [adv-ss] attempting to load "/home/filip/obs-portable-29.0.0-r23012-ubuntu-22.04/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.so"
info: [adv-ss] successfully loaded "/home/filip/obs-portable-29.0.0-r23012-ubuntu-22.04/obs-plugins/64bit/adv-ss-plugins/advanced-scene-switcher-opencv.so"
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'
QCssParser::parseColorValue: Specified color without alpha value but alpha given: 'rgb 0,0,0,0'
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
libDeckLinkAPI.so: kan ikke åbne delt objektfil: Ingen sådan fil eller filkatalog
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
warning: Failed to initialize module 'decklink.so'
warning: Failed to load 'da-DK' text for module: 'device-switcher.so'
info: [Device Switcher] loaded version 0.1.2
QLayout: Attempting to add QLayout "" to DeviceSwitcherDock "", which already has a layout
warning: Failed to load 'da-DK' text for module: 'dir-watch-media.so'
info: [Directory watch media] loaded version 0.6.1
warning: Failed to load 'da-DK' text for module: 'downstream-keyer.so'
info: [Downstream Keyer] loaded version 0.2.6
warning: Failed to load 'da-DK' text for module: 'dvd-screensaver.so'
warning: Failed to load 'da-DK' text for module: 'dynamic-delay.so'
info: [Dynamic Delay] loaded version 0.1.4
warning: Failed to load 'da-DK' text for module: 'freeze-filter.so'
info: [Freeze Filter] loaded version 0.3.3
warning: Failed to load 'da-DK' text for module: 'gradient-source.so'
info: [Gradient Source] loaded version 0.3.1
warning: Failed to load 'en-US' text for module: 'libtext-pango.so'
info: [pango]: Loaded system fontconfig
warning: Failed to load 'da-DK' text for module: 'linux-pipewire-audio.so'
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
warning: Failed to load 'da-DK' text for module: 'linux-vkcapture.so'
info: [linux-vkcapture] plugin loaded successfully (version 1.2.2)
warning: Failed to load 'da-DK' text for module: 'media-controls.so'
info: [Media Controls] loaded version 0.3.6
warning: Failed to load 'da-DK' text for module: 'move-transition.so'
info: [Move Transition] loaded version 2.8.1
warning: Failed to load 'en-US' text for module: 'obs-async-source-duplication.so'
info: [obs-async-source-duplication] plugin loaded successfully (version 0.4.1)
warning: Failed to load 'en-US' text for module: 'obs-audio-pan-filter.so'
info: [obs-audio-pan-filter] plugin loaded successfully (version 0.2.3)
info: [obs-browser]: Version 2.19.0
info: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures_143.2591+g4204d54+chromium-103.0.5060.134 (compiled)
warning: Failed to load 'da-DK' text for module: 'obs-color-monitor.so'
info: [obs-color-monitor] plugin loaded successfully (plugin version 0.4.3, API version 29.0.0)
warning: Failed to load 'da-DK' text for module: 'obs-command-source.so'
warning: Failed to load 'en-US' text for module: 'obs-face-tracker.so'
info: [obs-face-tracker] registering face_tracker_filter_info (version 0.7.0)
info: [obs-face-tracker] ft_docks_init: Adding face tracker dock menu action=0x564e0830ae80
info: NVENC supported
error: VAAPI: Failed to initialize display in vaapi_device_h264_supported
info: FFmpeg VAAPI H264 encoding not supported
info: [obs-gstreamer] build: 7dd3e69, gst-runtime: 1.20.3
warning: Failed to load 'en-US' text for module: 'obs-midi-mg.so'
info: [obs-midi-mg] Main -> Loading plugin...
info: [obs-midi-mg] Config -> Loading configuration...
info: [obs-midi-mg] Config -> Configuration file not found. Loading new data...
info: [obs-midi-mg] Config -> Configuration file data loaded. Extracting...
info: [obs-midi-mg] Config -> Configuration file data extraction complete.
info: [obs-midi-mg] Config -> Configuration loading complete.
info: [obs-midi-mg] Config -> New device detected.
info: [obs-midi-mg] Main -> Loading plugin using the Echo style...
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
Unknown property word-wrap
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_device_change(QString)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_message_type_change(QString)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_message_listen_continuous(bool)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_message_listen_once(bool)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_message_value_button_change(int)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_action_cat_change(int)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_action_sub_change(int)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_active_change(bool)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_preferences_click(bool)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_transfer_mode_change(short)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_transfer_bindings_click()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_interface_style_change(short)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_update_check()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_add_click()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_copy_click()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_remove_click()
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_list_selection_change(QListWidgetItem*)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_list_widget_state_change(QListWidgetItem*)
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_binding_drag(QModelIndex,int,int,QModelIndex,int)
info: [obs-midi-mg] Main -> Plugin loaded.
warning: Failed to load 'en-US' text for module: 'obs-multisource-effect.so'
info: [obs-multisource-effect] plugin loaded successfully (version 0.2.1)
warning: Failed to load 'en-US' text for module: 'obs-mute-filter.so'
info: [obs-mute-filter] plugin loaded successfully (version 0.2.2)
warning: Failed to load 'en-US' text for module: 'obs-rgb-levels-filter.so'
warning: Failed to load 'da-DK' text for module: 'obs-shaderfilter.so'
warning: Failed to load 'da-DK' text for module: 'obs-soundboard.so'
info: [obs-soundboard] Soundboard plugin version 1.1.0 is loaded
warning: Failed to load 'da-DK' text for module: 'obs-studio.so'
info: [obs-teleport] Version 0.6.1
warning: Failed to load 'en-US' text for module: 'obs-text-pthread.so'
info: [obs-text-pthread] plugin loaded successfully (version 2.0.2)
info: [obs-vaapi] version: 0.1.0, gst-runtime: 1.20.3
error: [obs-vaapi] vapostproc element not found
warning: Failed to initialize module 'obs-vaapi.so'
warning: Failed to load 'da-DK' text for module: 'obs-websocket-compat.so'
info: [obs-websocket 4.9.1-compat] you can haz websockets (version 4.9.1-compat)
info: [obs-websocket 4.9.1-compat] qt version (compile-time): 6.2.4 ; qt version (run-time): 6.2.4
info: [obs-websocket 4.9.1-compat] [obs_module_load] Linked ASIO Version: 101201
info: [obs-websocket 4.9.1-compat] module loaded!
info: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1)
info: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.2.4 | Qt version (run-time): 6.2.4
info: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201
info: [obs-websocket] [obs_module_load] Module loaded.
warning: Failed to load 'da-DK' text for module: 'recursion-effect.so'
info: [Recursion Effect] loaded version 0.0.6
warning: Failed to load 'da-DK' text for module: 'replay-source.so'
info: [Replay Source] loaded version 1.6.11
warning: Failed to load 'da-DK' text for module: 'scene-collection-manager.so'
info: [Scene Collection Manager] loaded version 0.0.8
warning: Failed to load 'da-DK' text for module: 'scene-notes-dock.so'
info: [Scene Notes Dock] loaded version 0.1.1
QLayout: Attempting to add QLayout "" to SceneNotesDock "SceneNotesDock", which already has a layout
warning: Failed to load 'da-DK' text for module: 'setting-docks.so'
info: [Setting Docks] loaded version 0.0.4
QLayout: Attempting to add QLayout "" to StreamDock "StreamDock", which already has a layout
QLayout: Attempting to add QLayout "" to StreamDock "StreamDock", which already has a layout
QLayout: Attempting to add QLayout "" to VideoDock "VideoDock", which already has a layout
QLayout: Attempting to add QLayout "" to BitrateDock "BitrateDock", which already has a layout
warning: Failed to load 'da-DK' text for module: 'source-clone.so'
info: [Source Clone] loaded version 0.1.1
warning: Failed to load 'da-DK' text for module: 'source-copy.so'
info: [Source Copy] loaded version 0.2.2
warning: Failed to load 'da-DK' text for module: 'source-dock.so'
info: [Source Dock] loaded version 0.3.4
warning: Failed to load 'da-DK' text for module: 'source-record.so'
info: [Source Record] loaded version 0.3.2
warning: Failed to load 'da-DK' text for module: 'source-switcher.so'
info: [Source Switcher] loaded version 0.4.1
Ulovlig instruktion (SIGILL) (smed kerne)
filip@gonzo:~/obs-portable-29.0.0-r23012-ubuntu-22.04$

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/obs-studio-portable/commit/e454cd26f271e152175d78d2e1159acd764933d7
