### ISSUE TITLE
segfault for r23319 on Mantic

### ISSUE THREAD

**Issue by DiogoConstantino** [wimpysworld/obs-studio-portable#42]
I'm trying to run r23319 on my Ubuntu 23.10, but I'm getting a segfault.

My OS is fully up-to-date.

While running the dependencies installation package libgles2-mesa fails to install (it doesn't exist), but Package libgles2-mesa-dev exists (it's a transitional package)

While starting obs, I get "Impossible to load the shared object, because the file or folder doesn't exist" for these:

```
error: os_dlopen(../../obs-plugins/64bit/obs-ffmpeg.so->../../obs-plugins/64bit/obs-ffmpeg.so): libavdevice.so.60: impossível abrir ficheiro-objecto partilhado: Ficheiro ou pasta inexistente

error: os_dlopen(../../obs-plugins/64bit/obs-websocket.so->../../obs-plugins/64bit/obs-websocket.so): libqrcodegencpp.so.1: impossível abrir ficheiro-objecto partilhado: Ficheiro ou pasta inexistente

error: os_dlopen(../../obs-plugins/64bit/obs-websocket.so->../../obs-plugins/64bit/obs-websocket.so): libqrcodegencpp.so.1: impossível abrir ficheiro-objecto partilhado: Ficheiro ou pasta inexistente
```

The entire output except the message saying there's segfault and core dumped are on an attached file:
[allout.txt](https://github.com/wimpysworld/obs-studio-portable/files/13545021/allout.txt)

Last few output lines are here:

```
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Cena':
info: ------------------------------------------------
error: Source ID 'ffmpeg_source' not found
error: Failed to create source 'Soundboard'!
info: User added scene 'Vertical Scene'
Falta de segmentação (núcleo despejado)

```

OBS does start in "safe mode".

**Comment by DiogoConstantino** [comment]
I installed libgles2-mesa-dev but it doesn't help.
Installing libavdevice60/mantic and libqrcodegencpp1/mantic does make it start.

**Comment by flexiondotorg** [comment]
Did you upgrade from an earlier release of OBS Studio Portable? 

If so, you need to run `sudo ./obs-dependencies` again to ensure everything is installed.
